/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.strangegrotto.clijournal;

import net.sourceforge.argparse4j.ArgumentParsers;
import net.sourceforge.argparse4j.inf.ArgumentParser;

public class Main {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        ArgumentParser parser = ArgumentParsers.newFor("Journal CLI").build()
                .description("CLI for interacting with a file-based journalling system");

        System.out.println(new Main().getGreeting());
    }
}
